//
//  loginWorker.swift
//  BankApp
//
//  Created by Andre Jardim Firmo on 18/06/20.
//  Copyright (c) 2020 Andre Jardim Firmo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

import Alamofire

protocol LoginRepositoryProtocol {
    func getRequestUser(request: Login.Request, completion:@escaping (Result<UserMapper, AFError>) -> Void)
}



class LoginRepository : LoginRepositoryProtocol{
    static let shared = LoginRepository()
    private lazy var apiRepository: APIRepository = {
        let manager = APIRepository()
        return manager
    }()

    func getRequestUser(request: Login.Request, completion: @escaping (Result<UserMapper, AFError>) -> Void) {
        apiRepository.createRequest(route: API.login(username: request.username, passwd: request.password)) { (results) in
            completion(results)
        }
    }
    
}

