//
//  loginModels.swift
//  BankApp
//
//  Created by Andre Jardim Firmo on 18/06/20.
//  Copyright (c) 2020 Andre Jardim Firmo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {
  // MARK: Use cases
    struct Request {
        let username: String
        let password: String
    }
    struct Response {
        let user: UserMapper?
    }
    
    struct ViewModel {
        
    }
}
