//
//  loginRouter.swift
//  BankApp
//
//  Created by Andre Jardim Firmo on 18/06/20.
//  Copyright (c) 2020 Andre Jardim Firmo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import UIKit

@objc protocol LoginRoutingLogic {
    func routeToSomewhere(login: LoginViewController, user: UserRealm)
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    func routeToSomewhere(login: LoginViewController, user: UserRealm) {
        
    }
    
    var dataStore: LoginDataStore?

    var navigationController: UIViewController

    init(navigationController: UIViewController) {
        self.navigationController = navigationController
    }
  // MARK: Routing and navigation

//    func routeToSomewhere(login: LoginViewController, user: UserRealm) {
//        login.dismiss(animated: false, completion: nil)
//        let homeViewController = HomeViewController(interactor: HomeInteractor(worker: HomeRepository(), user: user), router: HomeRouter(navigationController: navigationController), presenter: HomePresenter())
//        navigationController.present(homeViewController, animated: false, completion: nil)
//  }
}
