//
//  loginViewController.swift
//  BankApp
//
//  Created by Andre Jardim Firmo on 18/06/20.
//  Copyright (c) 2020 Andre Jardim Firmo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplay: class
{
    func showError(error: String)
    func setupUser(user: UserRealm)
    func displayHome(viewModel: Login.ViewModel)
}

class LoginViewController: UIViewController{
    
    //MARK: - IBOutlet
    
    @IBOutlet weak var userNameLb: UITextField!
    
    @IBOutlet weak var passwordLb: UITextField!
    
    
    //MARK: - Variables
  
    var router: LoginRouter
    private var interactor: LoginInteractor
    private var presenter: LoginPresenter

    //MARK: - Initializer
    
    init(interactor: LoginInteractor, router: LoginRouter, presenter: LoginPresenter) {
        self.interactor = interactor
        self.interactor.presenter = presenter
        self.presenter = presenter
        self.router = router
        super.init(nibName: nil, bundle: nil)
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
   // MARK: -  Object lifecycle
    override func viewDidLoad() {
       super.viewDidLoad()
       setup()
    }
    
    // MARK:  - Setup()
    private func setup(){
        presenter.viewController = self
        interactor.getLastUser()
    }
    
    //MARK: - IBACTION
    
    @IBAction func login(_ sender: Any) {
        let request = Login.Request(username: userNameLb.text ?? "", password: passwordLb.text ?? "")
        interactor.doSomething(request: request)
    }
    
    func login(){
        if let user = interactor.user{
            router.routeToSomewhere(login: self, user: user)
        }
    }
    
    
}

extension LoginViewController: LoginDisplay{
    
    func showError(error: String){
        
    }
    func setupUser(user: UserRealm){
        
    }
    func displayHome(viewModel: Login.ViewModel){
        
    }
    
    
}
