//
//  loginPresenter.swift
//  BankApp
//
//  Created by Andre Jardim Firmo on 18/06/20.
//  Copyright (c) 2020 Andre Jardim Firmo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol loginPresentationLogic
{
  func presentSomething(response: login.Something.Response)
}

class loginPresenter: loginPresentationLogic
{
  weak var viewController: loginDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: login.Something.Response)
  {
    let viewModel = login.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
