//
//  HomeRouter.swift
//  BankApp
//
//  Created by Andre Jardim Firmo on 18/06/20.
//  Copyright (c) 2020 Andre Jardim Firmo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
@objc protocol HomeRoutingLogic {
  func routeToLogin(home: HomeViewController)
}

class HomeRouter: NSObject, HomeRoutingLogic {
    
    var navigationController: UIViewController
    
    init(navigationController: UIViewController) {
        self.navigationController = navigationController
    }

  // MARK: Routing
    func routeToLogin(home: HomeViewController) {
        home.dismiss(animated: true, completion: nil)
        
//        let login = LoginViewController(interactor: LoginInteractor(repository: LoginRepository()), router: LoginRouter(navigationController: navigationController as! UINavigationController), presenter: LoginPresenter())
//        navigationController.present(login, animated: false, completion: nil)
    }
}
