//
//  HomeViewController.swift
//  BankApp
//
//  Created by Andre Jardim Firmo on 18/06/20.
//  Copyright (c) 2020 Andre Jardim Firmo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeDisplayLogic: class
{
  func displaySomething(viewModel: Home.ViewModel)
}

class HomeViewController: UIViewController, HomeDisplayLogic{
   
    
    

    
  //MARK: - IBOutlet
    
    @IBOutlet weak var userNameLb: UILabel!
    
    @IBOutlet weak var userAccontLb: UILabel!
    
    @IBOutlet weak var userBalanceLb: UILabel!
    
    @IBOutlet weak var tableview: UITableView!
    
  // MARK: - Object lifecycle
  
    var router: HomeRouter
    private var interector: HomeInteractor
    private var presenter: HomePresenter
    private var tableViewDataSource: HomeDataSource?

    init(interector: HomeInteractor, router: HomeRouter, presenter: HomePresenter) {
        self.interector = interector
        self.presenter = presenter
        self.router = router
        super.init(nibName: "HomeViewController", bundle: nil)
    }
    
    required init?(coder: NSCoder) {
       fatalError("init(coder:) has not been implemented")
    }
  
  // MARK: - View lifecycle
  
    
    override func viewDidLoad() {
        
        populateInformations()
        setupView()
            
       }
    
    private func setupView() {
           presenter.viewController = self
           
           HomeDataSource.setupHome(tableView: tableview)
           tableViewDataSource = HomeDataSource(presenter: presenter)
           tableview.dataSource = tableViewDataSource
           tableview.delegate = tableViewDataSource
       }
  
  // MARK: - PopulateInformations
  
  func populateInformations(){
    let request = Home.Request(userId: interector.user.userId)
    interector.getInfoStatements(request: request)
  }
  
    //MARK: - IBAction
    
    
    @IBAction func logout(_ sender: Any) {
        interector.removeUserFromRealm()
        router.routeToLogin(home: self)
    }
    
    
    
  func displaySomething(viewModel: Home.ViewModel){
    userNameLb.text = viewModel.response.user!.name
    userAccontLb.text = viewModel.response.user!.account
    userBalanceLb.text = viewModel.response.user!.balance
    tableview.reloadData()
    
  }
    
    
    
 
}
